#Application port
server:
  port: 8080
  
    
spring:
  application:
    name: product-service
  
  data:    mongodb:      host: localhost
      port: 27017
      database: shopping

#Valid Currencies      
product:
  currencies:
    - INR
    - USD
    - EUR      

