#Application port
server:
  port: 8080
  
    
spring:
  application:
    name: product-service
  
  data:    mongodb:      host: localhost
      port: 27017
      database: shopping
      
  boot:
    admin:
      client:
        url:
        - http://localhost:8081

#Logging      
logging:
  file:
    name: C:\Users\mayankjain02\Downloads\logs\product.log
    
  logback:
    rollingpolicy:
      max-file-size: 1 MB   
      
#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - beans
        - httptrace     

#Valid Currencies      
product:
  currencies:
    - INR
    - USD
    - EUR      

