#Application port
server:
  port: 8080
  
    
spring:
  application:
    name: product-service
  
  data:    mongodb:      host: localhost
      port: 27017
      database: shopping
      
logging:
  file:
    name: C:\Users\mayankjain02\Downloads\logs\product.log
    
  logback:
    rollingpolicy:
      max-file-size: 1 MB        

#Valid Currencies      
product:
  currencies:
    - INR
    - USD
    - EUR      

